### ISSUE TITLE
1.21 SUGGESTION | GOLD TO BE EXTENDED |

### ISSUE THREAD

**Issue by makumaku1974** [Stein-N/Resource-Nether-Ores#2]
Also are you able of to put the longer branch version of Gold like how they also extended the branch of ores for Copper and Iron?

**Comment by Stein-N** [comment]
Sry to ask, but what do you mean by extending? Like adding the normal Gold Ore to the Nether? 
When this is the case, i will not add the normal Gold Ore to the Nether since it already have the Nether Gold Ore, it will only drop the Gold Ingots but this is how Minecraft intended it.

**Comment by makumaku1974** [comment]
In minecraft terms. It's called Superveins which is big veins of ores like copper and iron in the overworld... And what i was suggesting is that Nether is full of Gold but the difference is that the Supervein for Gold in Nether is way risky. 

Probably a terrible concept but yeah.

![concept](https://github.com/Stein-N/Resource-Nether-Ores/assets/129804277/0223d293-acb4-421d-9066-2ab32894e6ba)

**Comment by Stein-N** [comment]
Ah ok, then i misunderstood your question.

This would seem a bit to much, i think the current Vanilla system is enough. And Gold isn't that of a usefull resource in a normal playthrough.
