### ISSUE TITLE
[Suggestion] Repackage "shipped" folder inside the mod into a "resourcepacks" folder.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Stein-N/Resource-Nether-Ores#3]
Other modders keep built-in packs in a folder within their mod called `resourcepacks`. You keep them in a folder called `shipped`. The former adds the packs only to the in-game resourcepacks list, which is good. Your method instead creates the resourcepack locally on the user's PC.

I find your method a bit of a problem. I'm a neat freak, so when mods have built-in packs I use, I remove them from the mod, and throw them in the config folder for Paxi to force load them on boot. If I don't use it, I delete it. That's where your way of shipping the packs becomes an issue, as removing the shipped folder from the mod causes the game to crash on boot.

I suggest repackaging the optional packs into a `resourcepacks` folder contained within the mod like other mods do, so they can be safely deleted if the user wills it.

**Comment by Stein-N** [comment]
I will have a look into it and update it as soon as possible, thanks for the suggestion.

**Comment by Stein-N** [comment]
Also can you provide an example of another Mod that has shipped resourcepacks?

**Comment by JENOVAAbsolute** [comment]
> Also can you provide an example of another Mod that has shipped resourcepacks?

Sorry for the late response. I had gone to bed shortly before you posted. I assume you're asking so you have an example to go off of. The images below shows how it's done with Continuity, but it's the same for all mods. I'll post a link to several mods that do this just in case.

https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.21
https://modrinth.com/mod/physicsmod/version/9hVF9EMT
https://modrinth.com/mod/eating-animation/version/1.9.71

![image](https://github.com/Stein-N/Resource-Nether-Ores/assets/60951301/a75f2674-d7eb-451d-95f5-fc70d4295f88)
![New Project](https://github.com/Stein-N/Resource-Nether-Ores/assets/60951301/95c17775-ecf6-4d39-a02b-a5fd3fdad631)

They put the `resourcepacks` folder in the same place you placed your shipped folder. Also, resourcepacks bundled with mods in this way don't need to be zipped.

**Comment by Stein-N** [comment]
Ahh ok, found everything i need, i think i can release a new version tomorrow. Thanks for your Suggestion and help.

**Comment by JENOVAAbsolute** [comment]
You're welcome, and thank you as well.
