### ISSUE TITLE
Nether Ores have no textures

### ISSUE THREAD

**Issue by Hydraxuz** [Stein-N/Resource-Nether-Ores#5]
This is for version 2.0.3 on NeoForge version 21.0.42
![2024-07-02_01 04 58](https://github.com/Stein-N/Resource-Nether-Ores/assets/96903828/fa4c795c-cb2c-49be-8e32-9ff754563380)

**Comment by Stein-N** [comment]
Will be fixed later that day.

**Comment by Hydraxuz** [comment]
Didn't mean to close it, also the blocks don't drop anything and cannot be mined properly

**Comment by Stein-N** [comment]
new version is uploaded. On Modrinth it is already available one Curseforge it needs to be approved.
